# Generated by Django 3.0.3 on 2020-07-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200726_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='emplyee',
            new_name='employee',
        ),
    ]
