# Generated by Django 3.0.3 on 2020-07-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20200726_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='employee',
            new_name='category',
        ),
    ]
