# Generated by Django 3.0.3 on 2020-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20200726_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='category',
        ),
        migrations.AddField(
            model_name='programmer',
            name='category',
            field=models.ManyToManyField(to='user_app.Category'),
        ),
    ]
